### ISSUE TITLE
error when creating new new AssociationSetFactory: "no attribute 'solr_assocs'"

### ISSUE THREAD

**Issue by realmarcin** [biolink/ontobio#130]
I'm getting an error when trying to create a new AssociationSetFactory:

from ontobio.ontol_factory import OntologyFactory
from ontobio.assoc_factory import AssociationSetFactory

HUMAN = 'NCBITaxon:9606'

ofactory = OntologyFactory()
afactory = AssociationSetFactory()
ont = ofactory.create('mondo')

aset = afactory.create(ontology=ont,
                       subject_category='disease',
                       object_category='phenotype',
                       taxon=HUMAN)

Error:

###
/Users/marcin/anaconda/lib/python3.6/site-packages/cachier/mongo_core.py:24: UserWarning: Cachier warning: pymongo was not found. MongoDB cores will not work.
  "Cachier warning: pymongo was not found. MongoDB cores will not work.")
Traceback (most recent call last):
  File "enrichment.py", line 16, in <module>
    taxon=HUMAN)
  File "/Users/marcin/anaconda/lib/python3.6/site-packages/ontobio/assoc_factory.py", line 62, in create
    taxon=taxon)
  File "/Users/marcin/anaconda/lib/python3.6/site-packages/cachier/core.py", line 178, in func_wrapper
    return _calc_entry(core, key, func, args, kwds)
  File "/Users/marcin/anaconda/lib/python3.6/site-packages/cachier/core.py", line 78, in _calc_entry
    func_res = func(*args, **kwds)
  File "/Users/marcin/anaconda/lib/python3.6/site-packages/ontobio/assoc_factory.py", line 152, in bulk_fetch_cached
    return bulk_fetch(**args)
  File "/Users/marcin/anaconda/lib/python3.6/site-packages/ontobio/golr/golr_associations.py", line 146, in bulk_fetch
    **kwargs)
  File "/Users/marcin/anaconda/lib/python3.6/site-packages/ontobio/golr/golr_associations.py", line 77, in search_associations_compact
    **kwargs
  File "/Users/marcin/anaconda/lib/python3.6/site-packages/ontobio/golr/golr_associations.py", line 33, in search_associations
    return q.exec()
  File "/Users/marcin/anaconda/lib/python3.6/site-packages/ontobio/golr/golr_query.py", line 846, in exec
    params = self.solr_params()
  File "/Users/marcin/anaconda/lib/python3.6/site-packages/ontobio/golr/golr_query.py", line 571, in solr_params
    self._set_solr(self.get_config().solr_assocs)
AttributeError: 'Session' object has no attribute 'solr_assocs'

**Comment by cmungall** [comment]
the quick fix is to copy the `conf/` folder from https://github.com/biolink/ontobio/tree/master/conf to your current dir... not ideal

**Comment by deepakunni3** [comment]
@cmungall @realmarcin It looks like this issue doesn't occur anymore since the `conf/` is now included as part of the ontobio library.
