### ISSUE TITLE
cachier is messing up the pipeline - lets make this optional

### ISSUE THREAD

**Issue by dougli1sqrd** [biolink/ontobio#321]
cachier caching mechanism in the ontol_factory is causing issues left and right. Let's make it so cachier doesn't harm the pipeline any longer.

**Comment by kltm** [comment]
Error in pipeline as:
```
[2019-05-02T09:51:20.895Z] Traceback (most recent call last):
[2019-05-02T09:51:20.895Z]   File "/var/lib/jenkins/workspace/eontology_pipeline
_snapshot-OLCOSBORX7TUJKUSVDZQNZDGXCRFSUQLNESYCP3R63U6FLW5DJ2A/go-site/pipeline/
mypyenv/lib/python3.5/site-packages/portalocker/portalocker.py", line 137, in lock
[2019-05-02T09:51:20.895Z]     fcntl.flock(file_.fileno(), flags)
[2019-05-02T09:51:20.895Z] BlockingIOError: [Errno 11] Resource temporarily unavailable
[2019-05-02T09:51:20.895Z] 
[2019-05-02T09:51:20.895Z] During handling of the above exception, another exception occurred:
[2019-05-02T09:51:20.895Z] 
[2019-05-02T09:51:20.895Z] Traceback (most recent call last):
[2019-05-02T09:51:20.895Z]   File "/var/lib/jenkins/workspace/eontology_pipeline_snapshot-OLCOSBORX7TUJKUSVDZQNZDGXCRFSUQLNESYCP3R63U6FLW5DJ2A/go-site/pipeline/mypyenv/lib/python3.5/site-packages/portalocker/utils.py", line 131, in acquire
[2019-05-02T09:51:20.895Z]     fh = self._get_lock(fh)
[2019-05-02T09:51:20.895Z]   File "/var/lib/jenkins/workspace/eontology_pipeline_snapshot-OLCOSBORX7TUJKUSVDZQNZDGXCRFSUQLNESYCP3R63U6FLW5DJ2A/go-site/pipeline/mypyenv/lib/python3.5/site-packages/portalocker/utils.py", line 180, in _get_lock
[2019-05-02T09:51:20.895Z]     portalocker.lock(fh, self.flags)
[2019-05-02T09:51:20.895Z]   File "/var/lib/jenkins/workspace/eontology_pipeline_snapshot-OLCOSBORX7TUJKUSVDZQNZDGXCRFSUQLNESYCP3R63U6FLW5DJ2A/go-site/pipeline/mypyenv/lib/python3.5/site-packages/portalocker/portalocker.py", line 141, in lock
[2019-05-02T09:51:20.895Z]     raise exceptions.LockException(exc_value, fh=file_)
[2019-05-02T09:51:20.895Z] portalocker.exceptions.LockException: [Errno 11] Resource temporarily unavailable
[2019-05-02T09:51:20.895Z] 
[2019-05-02T09:51:20.895Z] During handling of the above exception, another exception occurred:
[2019-05-02T09:51:20.895Z] 

[2019-05-02T09:51:20.895Z] Traceback (most recent call last):
[2019-05-02T09:51:20.895Z]   File "/var/lib/jenkins/workspace/eontology_pipeline_snapshot-OLCOSBORX7TUJKUSVDZQNZDGXCRFSUQLNESYCP3R63U6FLW5DJ2A/go-site/pipeline/mypyenv/lib/python3.5/site-packages/cachier/core.py", line 68, in _calc_entry
[2019-05-02T09:51:20.895Z]     core.set_entry(key, func_res)
[2019-05-02T09:51:20.895Z]   File "/var/lib/jenkins/workspace/eontology_pipeline_snapshot-OLCOSBORX7TUJKUSVDZQNZDGXCRFSUQLNESYCP3R63U6FLW5DJ2A/go-site/pipeline/mypyenv/lib/python3.5/site-packages/cachier/pickle_core.py", line 146, in set_entry
[2019-05-02T09:51:20.895Z]     self._save_cache(cache)
[2019-05-02T09:51:20.895Z]   File "/var/lib/jenkins/workspace/eontology_pipeline_snapshot-OLCOSBORX7TUJKUSVDZQNZDGXCRFSUQLNESYCP3R63U6FLW5DJ2A/go-site/pipeline/mypyenv/lib/python3.5/site-packages/cachier/pickle_core.py", line 121, in _save_cache
[2019-05-02T09:51:20.895Z]     with portalocker.Lock(fpath, mode='wb') as cache_file:
[2019-05-02T09:51:20.895Z]   File "/var/lib/jenkins/workspace/eontology_pipeline_snapshot-OLCOSBORX7TUJKUSVDZQNZDGXCRFSUQLNESYCP3R63U6FLW5DJ2A/go-site/pipeline/mypyenv/lib/python3.5/site-packages/portalocker/utils.py", line 197, in __enter__
[2019-05-02T09:51:20.895Z]     return self.acquire()
[2019-05-02T09:51:20.895Z]   File "/var/lib/jenkins/workspace/eontology_pipeline_snapshot-OLCOSBORX7TUJKUSVDZQNZDGXCRFSUQLNESYCP3R63U6FLW5DJ2A/go-site/pipeline/mypyenv/lib/python3.5/site-packages/portalocker/utils.py", line 157, in acquire
[2019-05-02T09:51:20.895Z]     raise exceptions.LockException(exception)
[2019-05-02T09:51:20.895Z] portalocker.exceptions.LockException: [Errno 11] Resource temporarily unavailable
[2019-05-02T09:51:20.895Z] 
[2019-05-02T09:51:20.895Z] During handling of the above exception, another exception occurred:
[2019-05-02T09:51:20.895Z] 
[2019-05-02T09:51:20.895Z] Traceback (most recent call last):
[2019-05-02T09:51:20.895Z]   File "/var/lib/jenkins/workspace/eontology_pipeline_snapshot-OLCOSBORX7TUJKUSVDZQNZDGXCRFSUQLNESYCP3R63U6FLW5DJ2A/go-site/pipeline/mypyenv/lib/python3.5/site-packages/portalocker/portalocker.py", line 137, in lock
[2019-05-02T09:51:20.895Z]     fcntl.flock(file_.fileno(), flags)
[2019-05-02T09:51:20.895Z] BlockingIOError: [Errno 11] Resource temporarily unavailable
[2019-05-02T09:51:20.895Z] 
[2019-05-02T09:51:20.895Z] During handling of the above exception, another exception occurred:
[2019-05-02T09:51:20.895Z] 
[2019-05-02T09:51:20.895Z] Traceback (most recent call last):
[2019-05-02T09:51:20.895Z]   File "/var/lib/jenkins/workspace/eontology_pipeline_snapshot-OLCOSBORX7TUJKUSVDZQNZDGXCRFSUQLNESYCP3R63U6FLW5DJ2A/go-site/pipeline/mypyenv/lib/python3.5/site-packages/portalocker/utils.py", line 131, in acquire
[2019-05-02T09:51:20.895Z]     fh = self._get_lock(fh)
[2019-05-02T09:51:20.895Z]   File "/var/lib/jenkins/workspace/eontology_pipeline_snapshot-OLCOSBORX7TUJKUSVDZQNZDGXCRFSUQLNESYCP3R63U6FLW5DJ2A/go-site/pipeline/mypyenv/lib/python3.5/site-packages/portalocker/utils.py", line 180, in _get_lock
[2019-05-02T09:51:20.895Z]     portalocker.lock(fh, self.flags)
[2019-05-02T09:51:20.895Z]   File "/var/lib/jenkins/workspace/eontology_pipeline_snapshot-OLCOSBORX7TUJKUSVDZQNZDGXCRFSUQLNESYCP3R63U6FLW5DJ2A/go-site/pipeline/mypyenv/lib/python3.5/site-packages/portalocker/portalocker.py", line 141, in lock
[2019-05-02T09:51:20.895Z]     raise exceptions.LockException(exc_value, fh=file_)
[2019-05-02T09:51:20.895Z] portalocker.exceptions.LockException: [Errno 11] Resource temporarily unavailable
[2019-05-02T09:51:20.895Z] 
[2019-05-02T09:51:20.895Z] During handling of the above exception, another exception occurred:
[2019-05-02T09:51:20.895Z] 
[2019-05-02T09:51:20.895Z] Traceback (most recent call last):
[2019-05-02T09:51:20.895Z]   File "mypyenv/bin/validate.py", line 618, in <module>
[2019-05-02T09:51:20.895Z]     cli()
[2019-05-02T09:51:20.895Z]   File "/var/lib/jenkins/workspace/eontology_pipeline_snapshot-OLCOSBORX7TUJKUSVDZQNZDGXCRFSUQLNESYCP3R63U6FLW5DJ2A/go-site/pipeline/mypyenv/lib/python3.5/site-packages/click/core.py", line 722, in __call__
[2019-05-02T09:51:20.895Z]     return self.main(*args, **kwargs)
[2019-05-02T09:51:20.895Z]   File "/var/lib/jenkins/workspace/eontology_pipeline_snapshot-OLCOSBORX7TUJKUSVDZQNZDGXCRFSUQLNESYCP3R63U6FLW5DJ2A/go-site/pipeline/mypyenv/lib/python3.5/site-packages/click/core.py", line 697, in main
[2019-05-02T09:51:20.895Z]     rv = self.invoke(ctx)
[2019-05-02T09:51:20.895Z]   File "/var/lib/jenkins/workspace/eontology_pipeline_snapshot-OLCOSBORX7TUJKUSVDZQNZDGXCRFSUQLNESYCP3R63U6FLW5DJ2A/go-site/pipeline/mypyenv/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
[2019-05-02T09:51:20.895Z]     return _process_result(sub_ctx.command.invoke(sub_ctx))
[2019-05-02T09:51:20.895Z]   File "/var/lib/jenkins/workspace/eontology_pipeline_snapshot-OLCOSBORX7TUJKUSVDZQNZDGXCRFSUQLNESYCP3R63U6FLW5DJ2A/go-site/pipeline/mypyenv/lib/python3.5/site-packages/click/core.py", line 895, in invoke
[2019-05-02T09:51:20.895Z]     return ctx.invoke(self.callback, **ctx.params)
[2019-05-02T09:51:20.895Z]   File "/var/lib/jenkins/workspace/eontology_pipeline_snapshot-OLCOSBORX7TUJKUSVDZQNZDGXCRFSUQLNESYCP3R63U6FLW5DJ2A/go-site/pipeline/mypyenv/lib/python3.5/site-packages/click/core.py", line 535, in invoke
[2019-05-02T09:51:20.895Z]     return callback(*args, **kwargs)
[2019-05-02T09:51:20.895Z]   File "mypyenv/bin/validate.py", line 589, in produce
[2019-05-02T09:51:20.895Z]     make_products(dataset, absolute_target, end_gaf, products, ontology_graph)
[2019-05-02T09:51:20.895Z]   File "mypyenv/bin/validate.py", line 36, in wrapper
[2019-05-02T09:51:20.895Z]     output_file = file_function(*args, **kwargs)
[2019-05-02T09:51:20.895Z]   File "mypyenv/bin/validate.py", line 331, in make_products
[2019-05-02T09:51:20.895Z]     transformer.translate(association)
[2019-05-02T09:51:20.895Z]   File "/var/lib/jenkins/workspace/eontology_pipeline_snapshot-OLCOSBORX7TUJKUSVDZQNZDGXCRFSUQLNESYCP3R63U6FLW5DJ2A/go-site/pipeline/mypyenv/lib/python3.5/site-packages/ontobio/rdfgen/assoc_rdfgen.py", line 222, in translate
[2019-05-02T09:51:20.895Z]     self.translate(association, and_xps)
[2019-05-02T09:51:20.895Z]   File "/var/lib/jenkins/workspace/eontology_pipeline_snapshot-OLCOSBORX7TUJKUSVDZQNZDGXCRFSUQLNESYCP3R63U6FLW5DJ2A/go-site/pipeline/mypyenv/lib/python3.5/site-packages/ontobio/rdfgen/assoc_rdfgen.py", line 278, in translate
[2019-05-02T09:51:20.895Z]     p = self.lookup_relation(ext['property'])
[2019-05-02T09:51:20.895Z]   File "/var/lib/jenkins/workspace/eontology_pipeline_snapshot-OLCOSBORX7TUJKUSVDZQNZDGXCRFSUQLNESYCP3R63U6FLW5DJ2A/go-site/pipeline/mypyenv/lib/python3.5/site-packages/ontobio/rdfgen/assoc_rdfgen.py", line 118, in lookup_relation
[2019-05-02T09:51:20.895Z]     ro = self.get_relation_ontology()
[2019-05-02T09:51:20.895Z]   File "/var/lib/jenkins/workspace/eontology_pipeline_snapshot-OLCOSBORX7TUJKUSVDZQNZDGXCRFSUQLNESYCP3R63U6FLW5DJ2A/go-site/pipeline/mypyenv/lib/python3.5/site-packages/ontobio/rdfgen/assoc_rdfgen.py", line 114, in get_relation_ontology
[2019-05-02T09:51:20.895Z]     self.ro = ofa.create('ro')
[2019-05-02T09:51:20.895Z]   File "/var/lib/jenkins/workspace/eontology_pipeline_snapshot-OLCOSBORX7TUJKUSVDZQNZDGXCRFSUQLNESYCP3R63U6FLW5DJ2A/go-site/pipeline/mypyenv/lib/python3.5/site-packages/ontobio/ontol_factory.py", line 76, in create
[2019-05-02T09:51:20.895Z]     return create_ontology(handle, **args)
[2019-05-02T09:51:20.895Z]   File "/var/lib/jenkins/workspace/eontology_pipeline_snapshot-OLCOSBORX7TUJKUSVDZQNZDGXCRFSUQLNESYCP3R63U6FLW5DJ2A/go-site/pipeline/mypyenv/lib/python3.5/site-packages/cachier/core.py", line 161, in func_wrapper
[2019-05-02T09:51:20.895Z]     return _calc_entry(core, key, func, args, kwds)
[2019-05-02T09:51:20.895Z]   File "/var/lib/jenkins/workspace/eontology_pipeline_snapshot-OLCOSBORX7TUJKUSVDZQNZDGXCRFSUQLNESYCP3R63U6FLW5DJ2A/go-site/pipeline/mypyenv/lib/python3.5/site-packages/cachier/core.py", line 72, in _calc_entry
[2019-05-02T09:51:20.895Z]     core.mark_entry_not_calculated(key)
[2019-05-02T09:51:20.895Z]   File "/var/lib/jenkins/workspace/eontology_pipeline_snapshot-OLCOSBORX7TUJKUSVDZQNZDGXCRFSUQLNESYCP3R63U6FLW5DJ2A/go-site/pipeline/mypyenv/lib/python3.5/site-packages/cachier/pickle_core.py", line 167, in mark_entry_not_calculated
[2019-05-02T09:51:20.895Z]     self._save_cache(cache)
[2019-05-02T09:51:20.895Z]   File "/var/lib/jenkins/workspace/eontology_pipeline_snapshot-OLCOSBORX7TUJKUSVDZQNZDGXCRFSUQLNESYCP3R63U6FLW5DJ2A/go-site/pipeline/mypyenv/lib/python3.5/site-packages/cachier/pickle_core.py", line 123, in _save_cache
[2019-05-02T09:51:20.895Z]     self._reload_cache()
[2019-05-02T09:51:20.895Z]   File "/var/lib/jenkins/workspace/eontology_pipeline_snapshot-OLCOSBORX7TUJKUSVDZQNZDGXCRFSUQLNESYCP3R63U6FLW5DJ2A/go-site/pipeline/mypyenv/lib/python3.5/site-packages/cachier/pickle_core.py", line 103, in _reload_cache
[2019-05-02T09:51:20.895Z]     with portalocker.Lock(fpath, mode='rb') as cache_file:
[2019-05-02T09:51:20.895Z]   File "/var/lib/jenkins/workspace/eontology_pipeline_snapshot-OLCOSBORX7TUJKUSVDZQNZDGXCRFSUQLNESYCP3R63U6FLW5DJ2A/go-site/pipeline/mypyenv/lib/python3.5/site-packages/portalocker/utils.py", line 197, in __enter__
[2019-05-02T09:51:20.895Z]     return self.acquire()
[2019-05-02T09:51:20.895Z]   File "/var/lib/jenkins/workspace/eontology_pipeline_snapshot-OLCOSBORX7TUJKUSVDZQNZDGXCRFSUQLNESYCP3R63U6FLW5DJ2A/go-site/pipeline/mypyenv/lib/python3.5/site-packages/portalocker/utils.py", line 157, in acquire
[2019-05-02T09:51:20.895Z]     raise exceptions.LockException(exception)
[2019-05-02T09:51:20.895Z] portalocker.exceptions.LockException: [Errno 11] Resource temporarily unavailable
```

**Comment by dougli1sqrd** [comment]
Fixed.

**Comment by RichardBruskiewich** [comment]
@dougli1sqrd (@cmungall?) I'm just wondering: did you post a fresh release of Ontobio with the "fix" you made 24 days ago? As it happens, the last release, 1.10.1 is dated 28  days ago...

I ask this because I tracked an instability in our NCATS workflow 2 using Ontobio to the @cachier wrapping the ontol_factory.  In essence, what is happening in the cachier wrapper is that is is calling ```core.wait_on_entry_calc(key)` within which fresh  ```Observer()``` threads are being spawned just before the code jumps into another recursive call on the ```core.wait_on_entry_calc(key)``` call. I was single stepping through this and, each time, a new Observer() thread was created. This results in a steady bloating of the program stack exhausting memory.

It is super strange that this was not previously a serious issue in our code, but to be frank, we've been noticing unexplainable memory and performance instabilities ... sound familiar?

**Comment by dougli1sqrd** [comment]
This can be closed since we have https://github.com/biolink/ontobio/issues/355
