### ISSUE TITLE
ontobio hard failing on monarch rgd ingest

### ISSUE THREAD

**Issue by kshefchek** [biolink/ontobio#462]
I haven't debugged but I'm guessing this is because the Aspect column is 'N'

Gaf file: ftp://ftp.rgd.mcw.edu/pub/data_release/annotated_rgd_objects_by_ontology/rattus_genes_mp

Stack trace:
```
Traceback (most recent call last):
  File "dipper-etl.py", line 285, in <module>
    main()
  File "dipper-etl.py", line 247, in main
    mysource.parse(args.limit)
  File "/var/lib/jenkins/workspace/build-rgd/dipper/sources/RGD.py", line 92, in parse
    assocs = p.parse(open(rgd_file, "r"))
  File "/var/lib/jenkins/workspace/build-rgd/venv/lib/python3.6/site-packages/ontobio/io/assocparser.py", line 342, in parse
    a = list(associations)
  File "/var/lib/jenkins/workspace/build-rgd/venv/lib/python3.6/site-packages/ontobio/io/assocparser.py", line 355, in association_generator
    parsed_result = self.parse_line(line)
  File "/var/lib/jenkins/workspace/build-rgd/venv/lib/python3.6/site-packages/ontobio/io/gafparser.py", line 240, in parse_line
    parsed = to_association(list(vals), report=self.report, qualifier_parser=self.qualifier_parser())
  File "/var/lib/jenkins/workspace/build-rgd/venv/lib/python3.6/site-packages/ontobio/io/gafparser.py", line 545, in to_association
    looked_up_rel = relations.lookup_label(relation)
  File "/var/lib/jenkins/workspace/build-rgd/venv/lib/python3.6/site-packages/ontobio/rdfgen/relations.py", line 49, in lookup_label
    return __relation_label_lookup.get(label.replace("_", " "), default)
AttributeError: 'NoneType' object has no attribute 'replace'
```

**Comment by kshefchek** [comment]
curious if this is on anyones radar, @cmungall @dougli1sqrd, if not I can take a closer look

**Comment by cmungall** [comment]
Fundamentally the issue here is that RGD is using GAF format for something other than gene/product->GO term functional annotation

They declare gaf-2.1 in header, I don't know if it's formally a violation of gaf-2.1, as it's a bit underspecified, but it will likely violate 2.2 [not sure, cc @kltm] 

I can see the attraction in overloading/adapting gaf for other kinds of subject or object type, but this strategy only works if formats are loose

A more principled approach would be to defined a more generic format, call it xaf. gaf could formally be a subset of xaf. note GO would not be responsible for defining xaf, but we can provide guidance. xaf would have its own parsers (the ontobio gaf parser could be a subclass; or it could be independent)

However, do we really need an additional format? Maybe kgx + biolink would fulfil the use cases for xaf?

as a practical recommendation for now I would recommend that ontobio GAF parser *not* be used for non-GOC-provided files.

**Comment by cmungall** [comment]
actually I am warming to the idea of making an XAF official
