### ISSUE TITLE
ogr bug?

### ISSUE THREAD

**Issue by dosumis** [biolink/ontobio#606]
Trying to use  ogr from local install following examples from docs I consistently get errors like this:

```
$ venv/bin/python bin/ogr.py -r cl neuron
/Users/davidos/Documents/GitHub/ontobio/venv/lib/python3.9/site-packages/rdflib_jsonld/__init__.py:9: DeprecationWarning: The rdflib-jsonld package has been integrated into rdflib as of rdflib==6.0.1.  Please remove rdflib-jsonld from your project's dependencies.
  warnings.warn(
Traceback (most recent call last):
  File "/Users/davidos/Documents/GitHub/ontobio/bin/ogr.py", line 197, in <module>
    main()
  File "/Users/davidos/Documents/GitHub/ontobio/bin/ogr.py", line 136, in main
    for id in ont.resolve_names(args.ids,
  File "/Users/davidos/Documents/GitHub/ontobio/ontobio/sparql/sparql_ontology.py", line 130, in resolve_names
    return super().resolve_names(names, synonyms, **args)
  File "/Users/davidos/Documents/GitHub/ontobio/ontobio/ontol.py", line 1006, in resolve_names
    for s in self.synonyms(nid):
  File "/Users/davidos/Documents/GitHub/ontobio/ontobio/sparql/sparql_ontology.py", line 100, in synonyms
    self.all_synonyms()
  File "/Users/davidos/Documents/GitHub/ontobio/ontobio/sparql/sparql_ontology.py", line 111, in all_synonyms
    self.add_synonym(syn)
  File "/Users/davidos/Documents/GitHub/ontobio/ontobio/ontol.py", line 875, in add_synonym
    if 'meta' not in n:
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by dosumis** [comment]
I now have this working - at least partly - from local files.    Perhaps the main problem is very uninformative error messages.
