### ISSUE TITLE
configurations are not installed when installing ontobio

### ISSUE THREAD

**Issue by lhannest** [biolink/ontobio#64]
I'm running on Ubuntu 14.04, using python3:

```shell
(venv) lance@Lance-PC:~/git/2017/ontobio_test$ python --version
Python 3.4.3
(venv) lance@Lance-PC:~/git/2017/ontobio_test$ pip --version
pip 9.0.1 from /home/lance/git/2017/ontobio_test/venv/lib/python3.4/site-packages (python 3.4)
```

```shell
(venv) lance@Lance-PC:~/git/2017/ontobio_test$ pip install ontobio
Collecting ontobio
  Using cached ontobio-0.2.10-py3-none-any.whl
Collecting scipy (from ontobio)
  Using cached scipy-0.19.1-cp34-cp34m-manylinux1_x86_64.whl
Collecting cachier (from ontobio)
  Using cached cachier-1.2.1.tar.gz
Collecting networkx (from ontobio)
  Using cached networkx-1.11-py2.py3-none-any.whl
Collecting pyyaml (from ontobio)
Collecting marshmallow (from ontobio)
  Using cached marshmallow-2.13.5-py2.py3-none-any.whl
Collecting requests (from ontobio)
  Using cached requests-2.18.1-py2.py3-none-any.whl
Collecting prefixcommons (from ontobio)
  Using cached prefixcommons-0.1.4-py3-none-any.whl
Collecting pysolr (from ontobio)
  Using cached pysolr-3.6.0-py2.py3-none-any.whl
Collecting sparqlwrapper (from ontobio)
Collecting numpy>=1.8.2 (from scipy->ontobio)
  Using cached numpy-1.13.0-cp34-cp34m-manylinux1_x86_64.whl
Collecting watchdog (from cachier->ontobio)
Collecting portalocker (from cachier->ontobio)
  Using cached portalocker-1.1.0-py2.py3-none-any.whl
Collecting decorator>=3.4.0 (from networkx->ontobio)
  Using cached decorator-4.0.11-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests->ontobio)
  Using cached certifi-2017.4.17-py2.py3-none-any.whl
Collecting urllib3<1.22,>=1.21.1 (from requests->ontobio)
  Using cached urllib3-1.21.1-py2.py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2 (from requests->ontobio)
  Using cached chardet-3.0.4-py2.py3-none-any.whl
Collecting idna<2.6,>=2.5 (from requests->ontobio)
  Using cached idna-2.5-py2.py3-none-any.whl
Collecting rdflib>=4.0 (from sparqlwrapper->ontobio)
  Using cached rdflib-4.2.2-py3-none-any.whl
Collecting pathtools>=0.1.1 (from watchdog->cachier->ontobio)
Collecting argh>=0.24.1 (from watchdog->cachier->ontobio)
  Using cached argh-0.26.2-py2.py3-none-any.whl
Collecting pyparsing (from rdflib>=4.0->sparqlwrapper->ontobio)
  Using cached pyparsing-2.2.0-py2.py3-none-any.whl
Collecting isodate (from rdflib>=4.0->sparqlwrapper->ontobio)
Building wheels for collected packages: cachier
  Running setup.py bdist_wheel for cachier ... error
  Complete output from command /home/lance/git/2017/ontobio_test/venv/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-r5b9tydd/cachier/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpwthrce5opip-wheel- --python-tag cp34:
  running bdist_wheel
  error: invalid truth value ''
  
  ----------------------------------------
  Failed building wheel for cachier
  Running setup.py clean for cachier
Failed to build cachier
Installing collected packages: numpy, scipy, pathtools, argh, pyyaml, watchdog, portalocker, cachier, decorator, networkx, marshmallow, certifi, urllib3, chardet, idna, requests, prefixcommons, pysolr, pyparsing, isodate, rdflib, sparqlwrapper, ontobio
  Running setup.py install for cachier ... done
Successfully installed argh-0.26.2 cachier-1.2.1 certifi-2017.4.17 chardet-3.0.4 decorator-4.0.11 idna-2.5 isodate-0.5.4 marshmallow-2.13.5 networkx-1.11 numpy-1.13.0 ontobio-0.2.10 pathtools-0.1.2 portalocker-1.1.0 prefixcommons-0.1.4 pyparsing-2.2.0 pysolr-3.6.0 pyyaml-3.12 rdflib-4.2.2 requests-2.18.1 scipy-0.19.1 sparqlwrapper-1.8.0 urllib3-1.21.1 watchdog-0.8.3
```
Now I try running app.py, which imports ontobio.
```shell
(venv) lance@Lance-PC:~/git/2017/ontobio_test$ python app.py 
/home/lance/git/2017/ontobio_test/venv/lib/python3.4/site-packages/cachier/mongo_core.py:24: UserWarning: Cachier warning: pymongo was not found. MongoDB cores will not work.
  "Cachier warning: pymongo was not found. MongoDB cores will not work.")
Traceback (most recent call last):
  File "app.py", line 10, in <module>
    results = q.exec()
  File "/home/lance/git/2017/ontobio_test/venv/lib/python3.4/site-packages/ontobio/golr/golr_query.py", line 349, in exec
    params = self.solr_params()
  File "/home/lance/git/2017/ontobio_test/venv/lib/python3.4/site-packages/ontobio/golr/golr_query.py", line 304, in solr_params
    self._set_solr(self.get_config().solr_search)
AttributeError: 'Session' object has no attribute 'solr_search'
```

And this is app.py:
```python
from ontobio.golr.golr_query import GolrSearchQuery

q = GolrSearchQuery(
        term='diabetes',
        category=['disease', 'gene'],
        rows=5,
        start=1
)

results = q.exec()

for d in results['docs']:
    print(d)
```

As you can see when I run app.py I get a warning about pymongo, but installing it doesn't make a difference (the warning just goes away).

**Comment by lhannest** [comment]
I think the problem is that the config.yaml file isn't being found. I'm passing the `solr_search` URL into the `GolSearchQuery` constructor and now it's working.

```python
q = GolrSearchQuery(
        term='diabetes',
        category=['disease', 'gene'],
        rows=5,
        start=1,
        url='https://solr.monarchinitiative.org/solr/search'
)
```

**Comment by lhannest** [comment]
This is a more robust solution that I've come up with:
```python
from ontobio.config import session
import os
abspath = os.path.abspath(os.path.dirname(__file__))
session.default_config_path = abspath + '/conf/config.yaml'
```
Where I just downloaded the conf/config.yaml file and placed it in my projects directory. With this the configurations are loaded properly. But this is pretty awkward, the configurations should be installed when you install ontobio.

**Comment by dougli1sqrd** [comment]
@lhannest You should try this again without your workaround. The issue was with creating an "empty" config, when no file is present. That should work correctly, but the error you saw was just a bug on our end. If you try again, you should get some kind of "default" config.

**Comment by lhannest** [comment]
@dougli1sqrd Thank you for taking a look, though I'm getting a different error now after having removed the local config.yaml file.
```
lance@Lance-PC:~/git/2017/biolink-beacon$ docker run -p 8080:5000 ncats:biolink
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
[2017-07-17 21:24:18,530] ERROR in app: Exception on /concepts [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.4/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/main.py", line 61, in get_concepts
    results = q.exec()
  File "/usr/local/lib/python3.4/dist-packages/ontobio/golr/golr_query.py", line 353, in exec
    params = self.solr_params()
  File "/usr/local/lib/python3.4/dist-packages/ontobio/golr/golr_query.py", line 307, in solr_params
    self._set_solr(self.get_config().solr_search)
  File "/usr/local/lib/python3.4/dist-packages/ontobio/golr/golr_query.py", line 232, in _set_solr
    self.solr = pysolr.Solr(endpoint.url, timeout=endpoint.timeout)
AttributeError: 'NoneType' object has no attribute 'url'
```

**Comment by lhannest** [comment]
@cmungall @dougli1sqrd I think this issue has come back. I noticed this output in my debug:

`[I 180301 10:08:30 config:191] using default session: <ontobio.config.Session object at 0x7f6f5d2b5f28>, path does not exist: conf/config.yaml`

I'm getting this error:
```
$ python
Python 3.4.3 (default, Nov 28 2017, 16:41:13) 
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from ontobio.golr.golr_query import GolrSearchQuery
/home/lance/git/2018/biolink-beacon/env/lib/python3.4/site-packages/cachier/mongo_core.py:24: UserWarning: Cachier warning: pymongo was not found. MongoDB cores will not work.
  "Cachier warning: pymongo was not found. MongoDB cores will not work.")
>>> q = GolrSearchQuery(term='diabetes')
>>> q.exec()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/lance/git/2018/biolink-beacon/env/lib/python3.4/site-packages/ontobio/golr/golr_query.py", line 353, in exec
    params = self.solr_params()
  File "/home/lance/git/2018/biolink-beacon/env/lib/python3.4/site-packages/ontobio/golr/golr_query.py", line 307, in solr_params
    self._set_solr(self.get_config().solr_search)
  File "/home/lance/git/2018/biolink-beacon/env/lib/python3.4/site-packages/ontobio/golr/golr_query.py", line 232, in _set_solr
    self.solr = pysolr.Solr(endpoint.url, timeout=endpoint.timeout)
AttributeError: 'NoneType' object has no attribute 'url'
```


This is the output from installing ontobio:
```
$ pip install ontobio
Collecting ontobio
  Using cached ontobio-0.2.31-py3-none-any.whl
Collecting pandas (from ontobio)
Collecting prefixcommons (from ontobio)
  Using cached prefixcommons-0.1.4-py3-none-any.whl
Collecting scipy (from ontobio)
  Using cached scipy-1.0.0-cp34-cp34m-manylinux1_x86_64.whl
Collecting jsobject (from ontobio)
Collecting marshmallow (from ontobio)
  Using cached marshmallow-2.15.0-py2.py3-none-any.whl
Collecting requests (from ontobio)
  Using cached requests-2.18.4-py2.py3-none-any.whl
Collecting sparqlwrapper (from ontobio)
Collecting click (from ontobio)
  Using cached click-6.7-py2.py3-none-any.whl
Collecting pyyaml (from ontobio)
Collecting networkx==1.11 (from ontobio)
  Using cached networkx-1.11-py2.py3-none-any.whl
Collecting pysolr (from ontobio)
Collecting cachier (from ontobio)
  Using cached cachier-1.2.2-py2.py3-none-any.whl
Collecting numpy>=1.9.0 (from pandas->ontobio)
  Using cached numpy-1.14.1-cp34-cp34m-manylinux1_x86_64.whl
Collecting python-dateutil>=2 (from pandas->ontobio)
  Using cached python_dateutil-2.6.1-py2.py3-none-any.whl
Collecting pytz>=2011k (from pandas->ontobio)
  Using cached pytz-2018.3-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests->ontobio)
  Using cached certifi-2018.1.18-py2.py3-none-any.whl
Collecting idna<2.7,>=2.5 (from requests->ontobio)
  Using cached idna-2.6-py2.py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2 (from requests->ontobio)
  Using cached chardet-3.0.4-py2.py3-none-any.whl
Collecting urllib3<1.23,>=1.21.1 (from requests->ontobio)
  Using cached urllib3-1.22-py2.py3-none-any.whl
Collecting rdflib>=4.0 (from sparqlwrapper->ontobio)
  Using cached rdflib-4.2.2-py3-none-any.whl
Collecting decorator>=3.4.0 (from networkx==1.11->ontobio)
  Using cached decorator-4.2.1-py2.py3-none-any.whl
Collecting watchdog (from cachier->ontobio)
Collecting portalocker (from cachier->ontobio)
  Using cached portalocker-1.1.0-py2.py3-none-any.whl
Collecting six>=1.5 (from python-dateutil>=2->pandas->ontobio)
  Using cached six-1.11.0-py2.py3-none-any.whl
Collecting isodate (from rdflib>=4.0->sparqlwrapper->ontobio)
  Using cached isodate-0.6.0-py2.py3-none-any.whl
Collecting pyparsing (from rdflib>=4.0->sparqlwrapper->ontobio)
  Using cached pyparsing-2.2.0-py2.py3-none-any.whl
Collecting pathtools>=0.1.1 (from watchdog->cachier->ontobio)
Collecting argh>=0.24.1 (from watchdog->cachier->ontobio)
  Using cached argh-0.26.2-py2.py3-none-any.whl
Installing collected packages: numpy, six, python-dateutil, pytz, pandas, pyyaml, certifi, idna, chardet, urllib3, requests, pathtools, argh, watchdog, portalocker, cachier, prefixcommons, scipy, jsobject, marshmallow, isodate, pyparsing, rdflib, sparqlwrapper, click, decorator, networkx, pysolr, ontobio
Successfully installed argh-0.26.2 cachier-1.2.2 certifi-2018.1.18 chardet-3.0.4 click-6.7 decorator-4.2.1 idna-2.6 isodate-0.6.0 jsobject-0.10.2 marshmallow-2.15.0 networkx-1.11 numpy-1.14.1 ontobio-0.2.31 pandas-0.22.0 pathtools-0.1.2 portalocker-1.1.0 prefixcommons-0.1.4 pyparsing-2.2.0 pysolr-3.7.0 python-dateutil-2.6.1 pytz-2018.3 pyyaml-3.12 rdflib-4.2.2 requests-2.18.4 scipy-1.0.0 six-1.11.0 sparqlwrapper-1.8.1 urllib3-1.22 watchdog-0.8.3
```

**Comment by dougli1sqrd** [comment]
Sorry it's taken me so long to respond to this. I'll need some time to look. In the meantime, you could try updating to our latest version (unless you're tracking master).
