### ISSUE TITLE
Current version of ontobio, in some cases, has trouble parsing GAF(?)

### ISSUE THREAD

**Issue by kltm** [biolink/ontobio#689]
In the pipeline output, we are seeing the error:

 ```
17:08:35  temp_output_gaf_path: /opt/go-site/pipeline/target/groups/cgd/cgd_temp.gaf
17:08:35  2024-08-21 00:08:35 [INFO] [PID:5250 TID:140489894875136] [assocparser.py:888 in `_ensure_file`]  Ensure file: None
17:08:35  Traceback (most recent call last):
17:08:35    File "/usr/local/bin/validate.py", line 999, in <module>
17:08:35      cli(obj={})
17:08:35    File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1157, in __call__
17:08:35      return self.main(*args, **kwargs)
17:08:35    File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1078, in main
17:08:35      rv = self.invoke(ctx)
17:08:35    File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1688, in invoke
17:08:35      return _process_result(sub_ctx.command.invoke(sub_ctx))
17:08:35    File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1434, in invoke
17:08:35      return ctx.invoke(self.callback, **ctx.params)
17:08:35    File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 783, in invoke
17:08:35      return __callback(*args, **kwargs)
17:08:35    File "/usr/local/lib/python3.10/dist-packages/click/decorators.py", line 33, in new_func
17:08:35      return f(get_current_context(), *args, **kwargs)
17:08:35    File "/usr/local/bin/validate.py", line 759, in produce
17:08:35      isoform_fixed_gaf = fix_pro_isoforms_in_gaf(end_gaf, matching_gpi_path, ontology_graph, temp_output_gaf_path)
17:08:35    File "/usr/local/bin/validate.py", line 792, in fix_pro_isoforms_in_gaf
17:08:35      gpis = gpiparser.parse(gpi_file, None)
17:08:35    File "/usr/local/lib/python3.10/dist-packages/ontobio/io/entityparser.py", line 40, in parse
17:08:35      for line in file:
17:08:35  TypeError: 'NoneType' object is not iterable
17:08:37  make: *** [Makefile:86: target/groups/cgd/cgd.group] Error 1
```

This is happening in at least seven of the files.

```
sjcarbon@moiraine:~/local/src/git/go-site[master]$:) grep Makefile: /tmp/consoleText
[2024-08-20T23:55:47.586Z] make: *** [Makefile:91: target/groups/sgn/sgn.group] Error 1
[2024-08-20T23:55:55.950Z] make: *** [Makefile:91: target/groups/pseudocap/pseudocap.group] Error 1
[2024-08-20T23:56:09.420Z] make: *** [Makefile:91: target/groups/genedb/genedb.group] Error 1
[2024-08-20T23:59:53.690Z] make: *** [Makefile:91: target/groups/reactome/reactome.group] Error 1
[2024-08-21T00:05:33.807Z] make: *** [Makefile:86: target/groups/tair/tair.group] Error 1
[2024-08-21T00:08:37.264Z] make: *** [Makefile:86: target/groups/cgd/cgd.group] Error 1
[2024-08-21T00:13:06.094Z] make: *** [Makefile:86: target/groups/rgd/rgd.group] Error 1
```

**Comment by sierra-moxon** [comment]
reopening because the PR just reverts the ontobio changes, does not fix this error.
