### ISSUE TITLE
GPI Parsing fails on zfin.gpi

### ISSUE THREAD

**Issue by dougli1sqrd** [biolink/ontobio#85]
If one creates a GpiParser and attempts to parse the uncompressed attached zfin.gpi file below, the following error occurs:
```
Traceback (most recent call last):
  File "tests/test_gpiparser.py", line 43, in <module>
    run_the_zfin_thing()
  File "tests/test_gpiparser.py", line 36, in run_the_zfin_thing
    results = p.parse(open("zfin.gpi", "r"))
  File "/Users/edouglass/lbl/biolink/ontobio/ontobio/io/entityparser.py", line 41, in parse
    parsed_line, new_ents  = self.parse_line(line)
  File "/Users/edouglass/lbl/biolink/ontobio/ontobio/io/entityparser.py", line 107, in parse_line
    properties] = vals
```

It's not clear yet if the file is at fault or if it's the parser. But in any case the parser should handle the wrong number of columns more gracefully.

Attached:
[zfin.gpi.zip](https://github.com/biolink/ontobio/files/1171674/zfin.gpi.zip)

**Comment by dougli1sqrd** [comment]
So I ran [goa_chicken_complex.gpi.zip](https://github.com/biolink/ontobio/files/1174885/goa_chicken_complex.gpi.zip) using the same test, and this completes succesfully. This makes me think the zfin.gpi is off.

**Comment by kltm** [comment]
I'll pop over and we can take a look at them.

**Comment by sierra-moxon** [comment]
Is there a way I can run the validator myself? thanks,Sierra (@ZFIN).

**Comment by kltm** [comment]
re #86

**Comment by kltm** [comment]
@sierra-moxon It should just be the python biolink/ontobio package: https://github.com/biolink/ontobio

**Comment by dougli1sqrd** [comment]
Not an easy way as of yet. I can try and make that happen through the command line next.

**Comment by kltm** [comment]
@dougli1sqrd your code above already does this, right?
https://github.com/biolink/ontobio/issues/85#issue-245260839

**Comment by dougli1sqrd** [comment]
@kltm @sierra-moxon Yeah it's true. If you copy that code into a file in ontobio, making sure to import those classes you could run it. But we will want a real command line entry into this. I'm working now to produce a command line entry point to this.

**Comment by cmungall** [comment]
Additionally, once registered we run a 'snapshot' dry-run release every 
day, so you'd get fast feedback that way.

**Comment by cmungall** [comment]
@dougli1sqrd any reason @sierra-moxon cannot just run ontobio-parse-assocs.py?
